helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/space-cadet
    forcestring: true
  - name: image.tag
    value: main@sha256:75bf41b7ccc257f2e219e99d314476514e9bdc1f076400c19b8f19f6fe5a0304
    forcestring: true
