helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/space-cadet
    forcestring: true
  - name: image.tag
    value: main@sha256:c8f2d575825c8aec45af55a3c03a7c530ccc7782f782dd1251035e9231d14ecd
    forcestring: true
