helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/space-cadet
    forcestring: true
  - name: image.tag
    value: main@sha256:b6afca279c3e81120ee2b5faf0f8e8bdf7ebcab0f80821d1787f46ae534dbaad
    forcestring: true
